test:
  clients:
    default:
      database: transaction_event_store_mongoid_test
      hosts:
        - localhost:27027
      options:
        read:
          mode: :primary
        write:
          w: 1
  options:
    use_utc: true
